/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType LifeEntry.
 *
 * @since 2026-07-09
 */
@PrimaryKeys({"id"})
public final class LifeEntry extends CloudDBZoneObject {
    private String id;

    @NotNull
    @DefaultValue(stringValue = "")
    private String userID;

    @NotNull
    @DefaultValue(stringValue = "")
    private String createdAt;

    private Integer mood;

    private Integer energy;

    private Integer stress;

    private Integer focus;

    private Double sleepHours;

    private Integer waterCups;

    private String activity;

    private String note;

    private Integer score;

    private String status;

    private String suggestion;

    public LifeEntry() {
        super(LifeEntry.class);
        this.userID = "";
        this.createdAt = "";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getUserID() {
        return userID;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setMood(Integer mood) {
        this.mood = mood;
    }

    public Integer getMood() {
        return mood;
    }

    public void setEnergy(Integer energy) {
        this.energy = energy;
    }

    public Integer getEnergy() {
        return energy;
    }

    public void setStress(Integer stress) {
        this.stress = stress;
    }

    public Integer getStress() {
        return stress;
    }

    public void setFocus(Integer focus) {
        this.focus = focus;
    }

    public Integer getFocus() {
        return focus;
    }

    public void setSleepHours(Double sleepHours) {
        this.sleepHours = sleepHours;
    }

    public Double getSleepHours() {
        return sleepHours;
    }

    public void setWaterCups(Integer waterCups) {
        this.waterCups = waterCups;
    }

    public Integer getWaterCups() {
        return waterCups;
    }

    public void setActivity(String activity) {
        this.activity = activity;
    }

    public String getActivity() {
        return activity;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getNote() {
        return note;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getScore() {
        return score;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }

    public String getSuggestion() {
        return suggestion;
    }

}
