/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnectclouddb.objecttypes;

import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;

/**
 * Definition of ObjectType UserSettings.
 *
 * @since 2026-07-10
 */
@PrimaryKeys({"userID"})
public final class UserSettings extends CloudDBZoneObject {
    private String userID;

    private String digestSelectedIds;

    private Boolean reminderEnabled;

    private Integer reminderHour;

    private Integer reminderMinute;

    private Double goalSleepHours;

    private Integer goalWaterCups;

    private Integer goalFocus;

    public UserSettings() {
        super(UserSettings.class);
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getUserID() {
        return userID;
    }

    public void setDigestSelectedIds(String digestSelectedIds) {
        this.digestSelectedIds = digestSelectedIds;
    }

    public String getDigestSelectedIds() {
        return digestSelectedIds;
    }

    public void setReminderEnabled(Boolean reminderEnabled) {
        this.reminderEnabled = reminderEnabled;
    }

    public Boolean getReminderEnabled() {
        return reminderEnabled;
    }

    public void setReminderHour(Integer reminderHour) {
        this.reminderHour = reminderHour;
    }

    public Integer getReminderHour() {
        return reminderHour;
    }

    public void setReminderMinute(Integer reminderMinute) {
        this.reminderMinute = reminderMinute;
    }

    public Integer getReminderMinute() {
        return reminderMinute;
    }

    public void setGoalSleepHours(Double goalSleepHours) {
        this.goalSleepHours = goalSleepHours;
    }

    public Double getGoalSleepHours() {
        return goalSleepHours;
    }

    public void setGoalWaterCups(Integer goalWaterCups) {
        this.goalWaterCups = goalWaterCups;
    }

    public Integer getGoalWaterCups() {
        return goalWaterCups;
    }

    public void setGoalFocus(Integer goalFocus) {
        this.goalFocus = goalFocus;
    }

    public Integer getGoalFocus() {
        return goalFocus;
    }
}
